############################################################
# Dockerfile to build gobgp QuaggaSRx container images 
# Based on CentOS 7
############################################################
#FROM centos:latest
FROM centos:7
MAINTAINER "Kyehwan Lee".
ENV container docker


################## BEGIN INSTALLATION ######################
RUN yum -y install epel-release 
RUN yum -y install wget libconfig libconfig-devel openssl openssl-devel libcrypto.so.* telnet less gcc
RUN yum -y install uthash-devel net-snmp readline-devel patch git net-snmp-config net-snmp-devel automake rpm-build

# ut-hash configuration
WORKDIR /root
RUN git clone https://github.com/usnistgov/NIST-BGP-SRx.git


# KeyVolt configuration
RUN mkdir -p /var/lib/bgpsec-keys/
VOLUME ["/var/lib/bgpsec-keys/"]


# SRxCryptoAPI configuration

WORKDIR /root/NIST-BGP-SRx/srx-crypto-api
RUN ./configure --prefix=/ CFLAGS="-O0 -g"
RUN make all install 


# SRxCryptoAPI post scripts 
RUN mv -f /etc/srxcryptoapi.conf.sample /etc/srxcryptoapi.conf \
        && touch /var/lib/bgpsec-keys/ski-list.txt \
        && touch /var/lib/bgpsec-keys/priv-ski-list.txt \
        && mv -f /etc/qsrx-router-key.cnf.sample /etc/qsrx-router-key.cnf \
        && cp -rf ./srxcryptoapi_lib64.conf /etc/ld.so.conf.d/ \
        && rm -rf /etc/ld.so.cache && ldconfig

#COPY srxcrpytoapi.conf /etc/srxcryptoapi.conf
CMD ["sleep", "infinity"]


############# DOCKER RUN command example #####################################
# docker run --rm -ti \
#       -v $PWD/keys/:/var/lib/bgpsec-keys/ \
#       <docker_name>
##############################################################################
