############################################################
# Dockerfile to build gobgp QuaggaSRx container images 
# Based on CentOS 7
############################################################
FROM centos:7
MAINTAINER "Kyehwan Lee".
ENV container docker


################## BEGIN INSTALLATION ######################
RUN yum -y install epel-release
RUN yum -y install wget libconfig libconfig-devel openssl openssl-devel libcrypto.so.* telnet less gcc
RUN yum -y install uthash-devel net-snmp readline-devel patch git net-snmp-config net-snmp-devel #automake rpm-build
WORKDIR /root


# KeyVolt configuration
VOLUME ["/var/lib/bgpsec-keys/"]



# SRxServer configuration
#
WORKDIR /root
RUN git clone https://github.com/usnistgov/NIST-BGP-SRx.git

WORKDIR /root/NIST-BGP-SRx
RUN ./buildBGP-SRx.sh -T -A


# QuaggaSRx configuration
#
WORKDIR /root

EXPOSE 2605 179
#ENTRYPOINT ["bgpd", "-u", "root"]
CMD ["sleep", "infinity"]


############# DOCKER RUN command example #####################################
# docker run --rm -ti -p 179:179 \
#       -v $PWD/bgpd.conf.bs1:/etc/quagga/bgpd.conf \
#       -v $PWD/keys/:/var/lib/bgpsec-keys/ \
#       <docker_name>
##############################################################################
