version: '3'
services:
    srx_server:
        container_name: srx_server
        image: srxsuite_src_github
        build:
            dockerfile: Dockerfile_srxsuite_src_github
            context: /opt/project/docker_test/test1
        volumes: 
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
            - /opt/project/docker_test/test1/srxcryptoapi.conf:/etc/srxcryptoapi.conf
            - /opt/project/docker_test/test1/srx_server.conf:/etc/srx_server.conf
        ports:
            - 17901:17901
        depends_on: 
            - rpkirtr_server
        command:
          srx_server -f /etc/srx_server.conf
        networks:
            bgp_net:
                ipv4_address: 172.37.0.100


    exabgpsrx:
        container_name: exabgpsrx
        image: exabgpsrx_src_github
        build:
            dockerfile: Dockerfile_exabgpsrx_src_github
            context: /opt/project/docker_test/test1
        volumes: 
            - /opt/project/docker_test/test1/exabgp.docker.conf:/etc/exabgp.conf 
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
        ports:
            - 1793:179
        privileged: true
        networks:
            bgp_net:
                ipv4_address: 172.37.0.3

    gobgpsrx:
        container_name: gobgpsrx
        image: gobgpsrx_src_github
        build:
            dockerfile: Dockerfile_gobgpsrx_src_github
            context: /opt/project/docker_test/test1
        volumes: 
            - /opt/project/docker_test/test1/gobgpd.docker.conf:/etc/gobgpd.conf 
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
        ports:
            - 1795:179
        privileged: true
        networks:
            bgp_net:
                ipv4_address: 172.37.0.5

    srxcryptoapi:
        container_name: srxcryptoapi
        image: srxcryptoapi_src_github
        build: 
            dockerfile: Dockerfile_srxcryptoapi_src_github
            context: /opt/project/docker_test/test1
        volumes: 
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
            - /opt/project/docker_test/test1/srxcryptoapi.conf:/etc/srxcryptoapi.conf
        command: sh -c "exit"
        networks:
            bgp_net:
                ipv4_address: 172.37.0.200


    bgpsecio:
        image: srxsuite_src_github
        volumes: 
            - /opt/project/docker_test/test1/bgpsecio.docker.conf:/etc/bgpsecio.conf
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
            - /opt/project/docker_test/test1/srxcryptoapi.conf:/etc/srxcryptoapi.conf
        ports:
            - 1792:179
        command: sh -c "sleep 10 && bgpsecio -f /etc/bgpsecio.conf"
        depends_on: 
            - quaggasrx
        networks:
            bgp_net:
                ipv4_address: 172.37.0.2


    rpkirtr_server:
        image: srxsuite_src_github
        volumes: 
            - /opt/project/docker_test/test1/rpkirtr_svr.conf:/etc/rpkirtr_svr.conf
        ports:
            - 323:323
        command:
            rpkirtr_svr -f /etc/rpkirtr_svr.conf
        networks:
            bgp_net:
                ipv4_address: 172.37.0.101


    quaggasrx:
        container_name: quaggasrx
        image: srxsuite_src_github
        volumes: 
            - /opt/project/docker_test/test1/quaggasrx.docker.conf:/etc/quagga/bgpd.conf
            - /opt/project/docker_test/test1/keys:/var/lib/bgpsec-keys
            - /opt/project/docker_test/test1/srxcryptoapi.conf:/etc/srxcryptoapi.conf
        ports:
            - 1794:179
            - 2605:2605
        privileged: true
        command:
            - /bin/sh 
            - -c 
            - |
              echo "sleep 5 seconds"
              sleep 5
              bgpd -u root -f /etc/quagga/bgpd.conf
        depends_on: 
            - srx_server
        networks:
            bgp_net:
                ipv4_address: 172.37.0.4


networks:
    bgp_net:
        ipam:
            driver: default
            config: 
                - subnet: 172.37.0.0/16

        
