############################################################
# Dockerfile to build gobgp QuaggaSRx container images 
# Based on CentOS 7
############################################################
FROM srxcryptoapi_src_github:latest
MAINTAINER "Kyehwan Lee".
ENV container docker


################## BEGIN INSTALLATION ######################
RUN yum -y install epel-release
RUN yum -y install wget libconfig libconfig-devel openssl openssl-devel libcrypto.so.* telnet less gcc
RUN yum -y install uthash-devel net-snmp readline-devel patch git net-snmp-config net-snmp-devel automake rpm-build autoconf libtool
WORKDIR /root


# KeyVolt configuration
VOLUME ["/var/lib/bgpsec-keys/"]



# SRxServer configuration
#
WORKDIR /root
#RUN git clone https://github.com/usnistgov/NIST-BGP-SRx.git
#RUN git clone https://github.com/kyehwanlee/TEST-BGP-SRx.git

WORKDIR /root/TEST-BGP-SRx/srx-crypto-api
RUN autoreconf -i
WORKDIR /root/TEST-BGP-SRx/bgpsec-io
RUN autoreconf -i
WORKDIR /root/TEST-BGP-SRx/srx-server
RUN autoreconf -i
WORKDIR /root/TEST-BGP-SRx/quagga-srx
RUN autoreconf -i
#WORKDIR /root/NIST-BGP-SRx
WORKDIR /root/TEST-BGP-SRx
RUN ./buildBGP-SRx.sh -T -A


# QuaggaSRx configuration
#
WORKDIR /root/TEST-BGP-SRx/srx-server
RUN make install prefix=/usr
WORKDIR /root/TEST-BGP-SRx/quagga-srx
RUN make install prefix=/usr
WORKDIR /root/TEST-BGP-SRx/srx-crypto-api
RUN make install prefix=/usr
WORKDIR /root/TEST-BGP-SRx/bgpsec-io
RUN make install prefix=/usr

WORKDIR /root/TEST-BGP-SRx

EXPOSE 2605 179 17900 17901
#ENTRYPOINT ["bgpd", "-u", "root"]
CMD ["sleep", "infinity"]


############# DOCKER RUN command example #####################################
# docker run --rm -ti -p 179:179 \
#       -v $PWD/bgpd.conf.bs1:/etc/quagga/bgpd.conf \
#       -v $PWD/keys/:/var/lib/bgpsec-keys/ \
#       <docker_name>
##############################################################################
